### ISSUE TITLE
Nexus and More

### ISSUE THREAD

**Issue by JoeKing2** [Heionbuji/SVGDB-frontend#1]
I have a leader request along with a few suggestions. Can you add the animations and voice lines for Nexus. Additionally, when will you be able to add the English voice lines for the Popularity Contest 4. If you're finding some difficulty, please let me know so I can possibly lend a hand.

**Comment by Heionbuji** [comment]
Nexus was already there, there was just a bit of an issue with it being recognized as a story leader (which it is, but also not). Fixed it now.
I just forgot to add those English voices, they should be there now. Thanks for the reminder.
